name: WeRead Sync
on:
  schedule:
    - cron: '0 8 * * *'  # 每天UTC 8点（北京时间16点）同步
  workflow_dispatch:     # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run Sync
        env:
          WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python src/main.py
